server:
  port: ${web_port}

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true

debug: true